settings:
  # Auto plant the crops that was harvested on a quest.
  AUTO_PLANT: true
  # Auto remove the crops that was planted on a quest.
  AUTO_REMOVE: true
  # Protect farmlands from fading to dirt via jumps.
  PROTECT_FARMLAND: true
  # Protect farm regions from block-break and block-place unless the player has a quest on it.
  PROTECT_FARM_REGION: true