name: FarmQuest
version: '${project.version}'
main: org.nandayo.farmquest.FarmQuest
api-version: '1.20'
authors: [ desaxx ]
commands:
  farmquest:
    aliases: fquest
    usage: /<command>
permissions:
  farmquest.admin:
    default: op
    children:
      farmquest.command.reload: true
      farmquest.command.createregion: true
      farmquest.command.farmmarker: true
      farmquest.command.farmmanager: true
      farmquest.command.items: true
      farmquest.command.removecompleted: true
      farmquest.protect.bypass: true
  farmquest.command.reload:
    default: op
  farmquest.command.createregion:
    default: op
  farmquest.command.farmmarker:
    default: op
  farmquest.command.farmmanager:
    default: op
  farmquest.command.items:
    default: op
  farmquest.command.removecompleted:
    default: op
  farmquest.protect.bypass:
    default: op