name: FarmQuest
version: '${project.version}'
main: org.nandayo.farmquest.FarmQuest
api-version: '1.17'
authors: [ desaxx ]
commands:
  farmquest:
    aliases: fquest
    usage: /<command>
permissions:
  farmquest.admin:
    default: op
    children:
      farmquest.command.*: true
      farmquest.protect.bypass: true
  farmquest.command.*:
    default: op
  farmquest.protect.bypass:
    default: op